export const categories = [
  { name: "Пиццы" },
  { name: "Комбо" },
  { name: "Закуски" },
  { name: "Коктейли" },
  { name: "Кофе" },
  { name: "Напитки" },
  { name: "Десерты" },
];
export const _ingredients = [
  {
    id: 1,
    name: "Сырный бортик",
    price: 80,
    imageUrl: "ingredients/yr8ettepctadmqozm3xg",
  },
  {
    id: 2,
    name: "Сливочная моцарелла",
    price: 50,
    imageUrl: "ingredients/pwrvnitzka4uwgpz2mkc",
  },
  {
    id: 3,
    name: "Сыры чеддер и пармезан",
    price: 60,
    imageUrl: "ingredients/ginazyq4nmxnfhhbtcih",
  },
  {
    id: 4,
    name: "Острый перец халапеньо",
    price: 30,
    imageUrl: "ingredients/muwstzzqaea92mrlpj4m",
  },
  {
    id: 5,
    name: "Нежный цыпленок",
    price: 55,
    imageUrl: "ingredients/qstwvsktsqkuzahylj07",
  },
  {
    id: 6,
    name: "Шампиньоны",
    price: 40,
    imageUrl: "ingredients/v4aljzx41kqr9o9wlrty",
  },
  {
    id: 7,
    name: "Бекон",
    price: 55,
    imageUrl: "ingredients/xposknqylrjrmkven4bh",
  },
  {
    id: 8,
    name: "Ветчина",
    price: 55,
    imageUrl: "ingredients/huyxjggg3a1ovhvubs40",
  },
  {
    id: 9,
    name: "Пикантная пепперони",
    price: 55,
    imageUrl: "ingredients/macycmuvkaay3jendrt4",
  },
  {
    id: 10,
    name: "Острая чоризо",
    price: 55,
    imageUrl: "ingredients/n0ibjpr36nvqjcxy82nm",
  },
  {
    id: 11,
    name: "Маринованные огурчики",
    price: 25,
    imageUrl: "ingredients/w5tdqmlralm0djpfph1f",
  },
  {
    id: 12,
    name: "Свежие томаты",
    price: 30,
    imageUrl: "ingredients/yj1rz6jxpqm6xlh6ftlp",
  },
  {
    id: 13,
    name: "Красный лук",
    price: 25,
    imageUrl: "ingredients/tbksgxaci2dsl1zzj6vw",
  },
  {
    id: 14,
    name: "Сочные ананасы",
    price: 30,
    imageUrl: "ingredients/tkhypyuqr0kg0agbw4wd",
  },
  {
    id: 15,
    name: "Итальянские травы",
    price: 15,
    imageUrl: "ingredients/mfwecmsbfky9yifqrpgg",
  },
  {
    id: 16,
    name: "Сладкий перец",
    price: 30,
    imageUrl: "ingredients/wprrlqr6do06wpvwudqr",
  },
  {
    id: 17,
    name: "Кубики брынзы",
    price: 55,
    imageUrl: "ingredients/kxyku27pxrq0rx7yxjke",
  },
  {
    id: 18,
    name: "Митболы",
    price: 70,
    imageUrl: "ingredients/xvc1dge43u2ycqwxael7",
  },
];


export const products = [
  { name: 'Омлет с ветчиной и грибами', imageUrl: "products/su8unqxridmyjipf6pnx", categoryId: 2 },
  { name: 'Омлет с пепперони', imageUrl: "products/hhehapcdsvor4ocu0sgt", categoryId: 2 },
  { name: 'Кофе Латте', imageUrl: "products/h7srhjic4nbab0pgjr72", categoryId: 2 },
  { name: 'Дэнвич ветчина и сыр', imageUrl: "products/oh1n2c7ddkydpkqyidna", categoryId: 3 },
  { name: 'Куриные наггетсы', imageUrl: "products/sqa3mmycr952w8e1lrye", categoryId: 3 },
  { name: 'Картофель из печи с соусом', imageUrl: "products/s6tdqtgfp8bmikcahj77", categoryId: 3 },
  { name: 'Додстер', imageUrl: "products/z3jxpmsebino10gq3wc2", categoryId: 3 },
  { name: 'Острый Додстер', imageUrl: "products/u1ttreifdsyodneaywlh", categoryId: 3 },
  { name: 'Банановый молочный коктейль', imageUrl: "products/gp4cyp8pnmxqlrjrjo7h", categoryId: 4 },
  { name: 'Карамельное яблоко молочный коктейль', imageUrl: "products/nlltkya1q1km85hor6ka", categoryId: 4 },
  { name: 'Молочный коктейль с печеньем Орео', imageUrl: "products/qmlhqw972q7koyu4oe72", categoryId: 4 },
  { name: 'Классический молочный коктейль', imageUrl: "products/j53xtaqfrtololzybh1k", categoryId: 4 },
  { name: 'Ореховый капучино', imageUrl: "products/dvcn12aymak4gnhsgqwp", categoryId: 5 },
  { name: 'Кофе Карамельный капучино', imageUrl: "products/hfazwwo6pj9uqopcwsyr", categoryId: 5 },
  { name: 'Кофе Кокосовый латте', imageUrl: "products/yuagjc3nqvio7pjspxs8", categoryId: 5 },
  { name: 'Кофе Американо', imageUrl: "products/r8hb4mwfhvt9bxvrbfnt", categoryId: 5 },
  { name: 'Кофе Латте', imageUrl: "products/q8wnbanddbabc5ktr0n8", categoryId: 5 },
];
